trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'sk8m8-api'

steps:
- task: Docker@2
  displayName: Build and push image to container registry
  inputs:
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: Sk8M8_API/dockerfile
    containerRegistry: AzureContainerRegistry
    tags: |
      $(Build.BuildId)
      latest
