kind: helm-release
apiVersion: 1.1
build:
  context: ..
  dockerfile: ../Dockerfile
install:
  chart: charts/sk8m8api
  set:
    replicaCount: 1
    image:
      repository: sk8m8containers.azurecr.io/sk8m8-api:latest
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to form the service's public URL: [space.s.][rootSpace.]sk8m8api.<random suffix>.<region>.azds.io
      # Customize the public URL by changing the 'sk8m8api' text between the $(rootSpacePrefix) and $(hostSuffix) tokens
      # For more information see https://aka.ms/devspaces/routing
      - $(spacePrefix)$(rootSpacePrefix)sk8m8api$(hostSuffix)
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
configurations:
  develop:
    build:
      useGitIgnore: true
      dockerfile: ../Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Debug}
    container:
      sync:
      - '**/Pages/**'
      - '**/Views/**'
      - '**/wwwroot/**'
      - '!**/*.{sln,csproj}'
      command:
      - dotnet
      - run
      - --no-restore
      - --no-build
      - --no-launch-profile
      - -c
      - ${BUILD_CONFIGURATION:-Debug}
      iterate:
        processesToKill:
        - dotnet
        - vsdbg
        - Sk8M8_API
        buildCommands:
        - - dotnet
          - build
          - --no-restore
          - -c
          - ${BUILD_CONFIGURATION:-Debug}
